export const foods=[
    {
        id:1,
        name:"Chicken Biriyani",
        image:"https://res.cloudinary.com/ditx1ptoe/image/upload/v1706970350/anju/bedzc8zx4btcwgotgpuy",
        price:199,
        category:"rice",
        owner:"The Dines",
    },{
        id:2,
        name:"Mutton Biriyani",
        image:"https://res.cloudinary.com/ditx1ptoe/image/upload/v1706970350/anju/xorvon0j8bhr0btysh6j",
        price:249,
        category:"rice",
        owner:"The Dines",
    },{
        id:3,
        name:"Burgor",
        image:"https://res.cloudinary.com/ditx1ptoe/image/upload/v1706970350/anju/grqnbahtdktidgw0b36g",
        price:99,
        category:"fastfood",
        owner:"The Dines",
    },{
        id:4,
        name:"Sandwich",
        image:"https://res.cloudinary.com/ditx1ptoe/image/upload/v1706970350/anju/z4h5ymz8vzasjkon3kv5",
        price:80,
        category:"fastfood",
        owner:"The Dines",
    },
    {
        id:5,
        name:"Chicken Biriyani",
        image:"https://res.cloudinary.com/ditx1ptoe/image/upload/v1706970350/anju/zj5riols2fz9ikdtpvae",
        price:189,
        category:"rice",
        owner:"Delish",
    },{
        id:6,
        name:"Beaf Biriyani ",
        image:"https://res.cloudinary.com/ditx1ptoe/image/upload/v1706970350/anju/rvxmbxwnlteugi5mqtsw",
        price:249,
        category:"food",
        owner:"Delish",
    },{
        id:7,
        name:"Zinger Burgor",
        image:"https://res.cloudinary.com/ditx1ptoe/image/upload/v1706970350/anju/hqdf4cj9dt8r7wptlylg",
        price:99,
        category:"fastfood",
        owner:"Delish",
    },{
        id:8,
        name:"Sandwich",
        image:"https://res.cloudinary.com/ditx1ptoe/image/upload/v1706970350/anju/wovsxr2w2hzzggnfxsn9",
        price:80,
        category:"fastfood",
        owner:"delish",
    },
    {
        id:9,
        name:"Mandhi (full)",
        image:"https://res.cloudinary.com/ditx1ptoe/image/upload/v1706970350/anju/sbdd8cxxdysac5q0himb",
        price:689,
        category:"rice",
        owner:"The dines",
    },{
        id:10,
        name:"Beaf Mandhi (full)",
        image:"https://res.cloudinary.com/ditx1ptoe/image/upload/v1706970350/anju/xifjdbujh4d6fcy849k3",
        price:749,
        category:"food",
        owner:"Delish",
    },{
        id:11,
        name:"Fruit salad",
        image:"https://res.cloudinary.com/ditx1ptoe/image/upload/v1706970350/anju/wkhu6cbaaetccwqoyyhh",
        price:199,
        category:"icecream",
        owner:"Luscious",
    },{
        id:12,
        name:"Falooda",
        image:"https://res.cloudinary.com/ditx1ptoe/image/upload/v1706970350/anju/es8grnwii1sjhelhnfhb",
        price:280,
        category:"icecream",
        owner:"Luscious",
    },
    
]

export const grocery=[
    {
        id:13,
        name:"Rice 1kg",
        image:"https://res.cloudinary.com/ditx1ptoe/image/upload/v1706970350/anju/c1e4vkmvxyzewisw8rbt",
        price:32,
        category:"riceg",
        owner:"Shimla",
    },{
        id:14,
        name:"Sugar 1kg",
        image:"https://res.cloudinary.com/ditx1ptoe/image/upload/v1706970350/anju/hwby1tzrj2hz1stl5iqh",
        price:50,
        category:"sugar",
        owner:"Shimla",
    },{
        id:15,
        name:"Salt 1kg",
        image:"https://res.cloudinary.com/ditx1ptoe/image/upload/v1706970350/anju/j74goli9b7dhglo55dqs",
        price:9,
        category:"salt",
        owner:"Shimla",
    },{
        id:16,
        name:"Chilli powder 1kg",
        image:"https://res.cloudinary.com/ditx1ptoe/image/upload/v1706970350/anju/vj9tr5uk82nzr6ci05te",
        price:100,
        category:"chilli",
        owner:"Akg groceries",
    },
    {
        id:17,
        name:"Banana",
        image:"https://res.cloudinary.com/ditx1ptoe/image/upload/v1706970350/anju/aol5oxk7tkytbwpbvfte",
        price:39,
        category:"fruit",
        owner:"Akg groceries",
    },{
        id:18,
        name:"Graps",
        image:"https://res.cloudinary.com/ditx1ptoe/image/upload/v1706970350/anju/rg9hkbc1vv7c1hhjxjo8",
        price:120,
        category:"fruit",
        owner:"Akg groceries",
    },{
        id:19,
        name:"Milk Made",
        image:"https://res.cloudinary.com/ditx1ptoe/image/upload/v1706970350/anju/pcl0gsaljaqxxprssev6",
        price:149,
        category:"readymade",
        owner:"Shimla",
    },{
        id:20,
        name:"Pickle (cut-mango)",
        image:"https://res.cloudinary.com/ditx1ptoe/image/upload/v1706970350/anju/gqseibkhvwhqku55qsmv",
        price:30,
        category:"pickle",
        owner:"Akg groceries",
    },
    {
        id:21,
        name:"Pickle (lemon)",
        image:"https://res.cloudinary.com/ditx1ptoe/image/upload/v1706970350/anju/xldwjqvskikuvkbsmwr5",
        price:30,
        category:"pickle",
        owner:"Shimla",
    },{
        id:22,
        name:"Green Apple",
        image:"https://res.cloudinary.com/ditx1ptoe/image/upload/v1706970350/anju/ncgtmwcfhecu46cx0dzf",
        price:249,
        category:"fruit",
        owner:"Shimla",
    },{
        id:23,
        name:"Green Tea Powder (1kg)",
        image:"https://res.cloudinary.com/ditx1ptoe/image/upload/v1706970350/anju/mdijfjaltwqdljylauui",
        price:1299,
        category:"chaya",
        owner:"Priyam",
    },{
        id:24,
        name:"Oil",
        image:"https://res.cloudinary.com/ditx1ptoe/image/upload/v1706970350/anju/nqttee6yurkw6igvhwac",
        price:160,
        category:"Oil",
        owner:"Priyam",
    },
    {
        id:25,
        name:"Coconut Oil (1L)",
        image:"https://res.cloudinary.com/ditx1ptoe/image/upload/v1706970350/anju/k02ek9rnvykaehibzfee",
        price:150,
        category:"Oil",
        owner:"Priyam",  
    }
]

export const medicine=[
    {
        id:26,
        name:"Anti Biotic",
        image:"https://res.cloudinary.com/ditx1ptoe/image/upload/v1707293905/anju/xwmyxmrao2fzaowthvsm.jpg",
        price:12,
        category:"antibiotic",
        owner:"Neethi Medicals",
    },{
        id:27,
        name:"Dolo (per piece)",
        image:"https://res.cloudinary.com/ditx1ptoe/image/upload/v1707294060/anju/m3xfh7w0cfana12vgyu0.webp",
        price:5,
        category:"antibiotic",
        owner:"Neethi Medicals",
    },{
        id:28,
        name:"Telmikind H (strip)",
        image:"https://res.cloudinary.com/ditx1ptoe/image/upload/v1707294129/anju/q5hbtyobjlmtrncjybif.jpg",
        price:120,
        category:"colo",
        owner:"Neethi Medicals",
    },
    {
        id:29,
        name:"Glycomet GP2",
        image:"https://res.cloudinary.com/ditx1ptoe/image/upload/v1707294194/anju/cfdbcy3i38vvq94vinv1.jpg",
        price:150,
        category:"diabetis",
        owner:"Vivekandanda",
    },{
        id:30,
        name:"Liponorm 20",
        image:"https://res.cloudinary.com/ditx1ptoe/image/upload/v1707294266/anju/c7vytezt9kk4re8v7cyp.webp",
        price:120,
        category:"colo",
        owner:"Vivekandanda",
    },{
        id:31,
        name:"Paracetamol",
        image:"https://res.cloudinary.com/ditx1ptoe/image/upload/v1707294345/anju/ews296ni2un76w4nhhzv.webp",
        price:5,
        category:"antibiotic",
        owner:"Vivekandanda",
    },{
        id:32,
        name:"Cyra -D",
        image:"https://res.cloudinary.com/ditx1ptoe/image/upload/v1707294462/anju/e7h0bohwtdjbveivdbbq.webp",
        price:28,
        category:"gas",
        owner:"Vivekandanda",
    },
    {
        id:33,
        name:"Amoxilin",
        image:"https://res.cloudinary.com/ditx1ptoe/image/upload/v1707293965/anju/r7x4xixj10ce23h3s2ps.jpg",
        price:35,
        category:"antibiotic",
        owner:"Aster medicals",
    },{
        id:34,
        name:"Lacticol Monohydrate",
        image:"https://res.cloudinary.com/ditx1ptoe/image/upload/v1707294537/anju/rbth5bah7a8bvrizqd46.webp",
        price:349,
        category:"gas",
        owner:"Aster medicals",
    },{
        id:35,
        name:"Aspirin",
        image:"https://res.cloudinary.com/ditx1ptoe/image/upload/v1707294610/anju/hhmuaz5almwvs4js25dw.webp",
        price:101,
        category:"pain killer",
        owner:"Aster medicals",
    },{
        id:36,
        name:"Amlodipine",
        image:"https://res.cloudinary.com/ditx1ptoe/image/upload/v1707294725/anju/t9en8x4dxxtouzadt4gv.jpg",
        price:21,
        category:"heart",
        owner:"Aster medicals",
    },
    
]